In [63]:
import numpy as np
import copy

In [2]:
f = open("PAAD__RNAExp.txt","r")

In [3]:
f

<_io.TextIOWrapper name='PAAD__RNAExp.txt' mode='r' encoding='cp1252'>

In [4]:
dt = f.readlines()

In [9]:
l = []
for i in range(len(dt)):
    l.append(dt[i].split("\t"))

In [10]:
f.close()

In [23]:
len(l)

20531

In [14]:
f = open("clinical__nationwidechildrens.org_clinical_patient_paad.txt","r")
dt2 = f.readlines()
l2 = []
for i in range(len(dt2)):
    l2.append(dt2[i].split("\t"))

In [24]:
len(l2)

188

In [22]:
f.close()

In [43]:
for i in range(len(l)):
    l[i][184] = l[i][184].split("\n")[0]

In [44]:
l[0]

['GeneSymbol',
 'EntrezID',
 'TCGA-2J-AAB1-01A-11R-A41B-07',
 'TCGA-2J-AAB4-01A-12R-A41B-07',
 'TCGA-2J-AAB6-01A-11R-A41B-07',
 'TCGA-2J-AAB8-01A-12R-A41B-07',
 'TCGA-2J-AAB9-01A-11R-A41B-07',
 'TCGA-2J-AABA-01A-21R-A41B-07',
 'TCGA-2J-AABE-01A-12R-A41B-07',
 'TCGA-2J-AABF-01A-31R-A41B-07',
 'TCGA-2J-AABH-01A-21R-A41B-07',
 'TCGA-2J-AABI-01A-12R-A41B-07',
 'TCGA-2J-AABK-01A-31R-A41B-07',
 'TCGA-2J-AABO-01A-21R-A41B-07',
 'TCGA-2J-AABP-01A-11R-A41B-07',
 'TCGA-2J-AABR-01A-11R-A41B-07',
 'TCGA-2J-AABT-01A-11R-A41B-07',
 'TCGA-2J-AABU-01A-11R-A41B-07',
 'TCGA-2J-AABV-01A-12R-A41B-07',
 'TCGA-2L-AAQA-01A-21R-A38C-07',
 'TCGA-2L-AAQE-01A-11R-A39D-07',
 'TCGA-2L-AAQI-01A-12R-A39D-07',
 'TCGA-2L-AAQJ-01A-12R-A39D-07',
 'TCGA-2L-AAQL-01A-11R-A38C-07',
 'TCGA-2L-AAQM-01A-11R-A39D-07',
 'TCGA-3A-A9I5-01A-11R-A38C-07',
 'TCGA-3A-A9I7-01A-21R-A38C-07',
 'TCGA-3A-A9I9-01A-11R-A38C-07',
 'TCGA-3A-A9IB-01A-21R-A39D-07',
 'TCGA-3A-A9IC-01A-11R-A38C-07',
 'TCGA-3A-A9IH-01A-12R-A39D-07',
 'TCGA-3A-A9IJ-

In [48]:
for i in range(len(l2)):
    l2[i][76] = l2[i][76].split("\n")[0]

In [55]:
l2[2]

['CDE_ID:',
 'CDE_ID:2673794',
 'CDE_ID:',
 'CDE_ID:3027106',
 'CDE_ID:3081934',
 'CDE_ID:3124492',
 'CDE_ID:3288124',
 'CDE_ID:3088492',
 'CDE_ID:3088528',
 'CDE_ID:2200604',
 'CDE_ID:3008233',
 'CDE_ID:2192199',
 'CDE_ID:2192217',
 'CDE_ID:3382736',
 'CDE_ID:3382737',
 'CDE_ID:2896960',
 'CDE_ID:2757941',
 'CDE_ID:2757948',
 'CDE_ID:3121809',
 'CDE_ID:2200396',
 'CDE_ID:3',
 'CDE_ID:3086388',
 'CDE_ID:3086383',
 'CDE_ID:2785839',
 'CDE_ID:3385981',
 'CDE_ID:64215',
 'CDE_ID:2608702',
 'CDE_ID:2722309',
 'CDE_ID:3045435',
 'CDE_ID:3203106',
 'CDE_ID:3045439',
 'CDE_ID:3203222',
 'CDE_ID:5',
 'CDE_ID:3008273',
 'CDE_ID:3165475',
 'CDE_ID:2759550',
 'CDE_ID:2554674',
 'CDE_ID:2390921',
 'CDE_ID:2181650',
 'CDE_ID:2228604',
 'CDE_ID:2228610',
 'CDE_ID:2955385',
 'CDE_ID:2201918',
 'CDE_ID:3457767',
 'CDE_ID:3114013',
 'CDE_ID:3124961',
 'CDE_ID:3197322',
 'CDE_ID:3457768',
 'CDE_ID:3457760',
 'CDE_ID:3457771',
 'CDE_ID:2436860',
 'CDE_ID:3457764',
 'CDE_ID:2005312',
 'CDE_ID:2786727',
 '

In [56]:
l[1]

['?',
 '100133144',
 '8.5512',
 '23.9941',
 '1.7836',
 '3.5159',
 '1.0718',
 '12.5881',
 '6.2957',
 '13.5235',
 '5.3397',
 '14.5972',
 '13.8306',
 '2.7724',
 '0',
 '8.5158',
 '2.7472',
 '10.1856',
 '14.1732',
 '39.4772',
 '9.7683',
 '14.6922',
 '6.0495',
 '0',
 '5.9763',
 '4.0156',
 '1.6357',
 '9.4278',
 '4.7002',
 '7.3333',
 '21.0551',
 '1.9843',
 '14.1555',
 '5.1617',
 '22.9251',
 '22.071',
 '21.9264',
 '9.4508',
 '6.2242',
 '6.2277',
 '18.461',
 '18.2255',
 '4.0956',
 '17.1466',
 '7.9535',
 '8.5425',
 '5.501',
 '8.6169',
 '10.1435',
 '5.5257',
 '11.6403',
 '22.1817',
 '1.4527',
 '13.0654',
 '5.7154',
 '0',
 '10.6533',
 '0.7023',
 '10.732',
 '16.6385',
 '6.6345',
 '16.9595',
 '20.2221',
 '6.9298',
 '6.4359',
 '6.9798',
 '8.7529',
 '1.607',
 '6.3662',
 '34.5185',
 '15.3481',
 '12.0811',
 '22.0314',
 '21.3901',
 '3.9322',
 '6.3991',
 '6.4858',
 '7.9376',
 '5.0482',
 '3.8386',
 '0.0919',
 '7.1048',
 '8.2213',
 '4.1976',
 '1.681',
 '11.1265',
 '6.406',
 '11.2505',
 '10.4341',
 '10.783',


In [66]:
l = np.array(l).T

In [67]:
l

array([['GeneSymbol', '?', '?', ..., 'ZZZ3', 'psiTPTE22', 'tAKR'],
       ['EntrezID', '100133144', '100134869', ..., '26009', '387590',
        '389932'],
       ['TCGA-2J-AAB1-01A-11R-A41B-07', '8.5512', '8.522', ...,
        '616.0976', '45.3659', '0'],
       ...,
       ['TCGA-YH-A8SY-01A-11R-A37L-07', '8.4755', '4.375', ..., '375',
        '58.4112', '0'],
       ['TCGA-YY-A8LH-01A-11R-A36G-07', '6.3411', '24.5265', ...,
        '330.7243', '5.2916', '0'],
       ['TCGA-Z5-AAPL-01A-12R-A41B-07', '0', '11.396', ..., '695.1567',
        '42.1652', '0']], dtype='<U28')

In [64]:
gt = copy.deepcopy(l[0])

In [74]:
gt[3].split("-")[4][1]

'2'

In [88]:
gt

['GeneSymbol',
 'EntrezID',
 'TCGA-2J-AAB1-01A-11R-A41B-07',
 'TCGA-2J-AAB4-01A-12R-A41B-07',
 'TCGA-2J-AAB6-01A-11R-A41B-07',
 'TCGA-2J-AAB8-01A-12R-A41B-07',
 'TCGA-2J-AAB9-01A-11R-A41B-07',
 'TCGA-2J-AABA-01A-21R-A41B-07',
 'TCGA-2J-AABE-01A-12R-A41B-07',
 'TCGA-2J-AABF-01A-31R-A41B-07',
 'TCGA-2J-AABH-01A-21R-A41B-07',
 'TCGA-2J-AABI-01A-12R-A41B-07',
 'TCGA-2J-AABK-01A-31R-A41B-07',
 'TCGA-2J-AABO-01A-21R-A41B-07',
 'TCGA-2J-AABP-01A-11R-A41B-07',
 'TCGA-2J-AABR-01A-11R-A41B-07',
 'TCGA-2J-AABT-01A-11R-A41B-07',
 'TCGA-2J-AABU-01A-11R-A41B-07',
 'TCGA-2J-AABV-01A-12R-A41B-07',
 'TCGA-2L-AAQA-01A-21R-A38C-07',
 'TCGA-2L-AAQE-01A-11R-A39D-07',
 'TCGA-2L-AAQI-01A-12R-A39D-07',
 'TCGA-2L-AAQJ-01A-12R-A39D-07',
 'TCGA-2L-AAQL-01A-11R-A38C-07',
 'TCGA-2L-AAQM-01A-11R-A39D-07',
 'TCGA-3A-A9I5-01A-11R-A38C-07',
 'TCGA-3A-A9I7-01A-21R-A38C-07',
 'TCGA-3A-A9I9-01A-11R-A38C-07',
 'TCGA-3A-A9IB-01A-21R-A39D-07',
 'TCGA-3A-A9IC-01A-11R-A38C-07',
 'TCGA-3A-A9IH-01A-12R-A39D-07',
 'TCGA-3A-A9IJ-

In [89]:
labels = []

for i in range(len(gt)):
    try:
        if gt[i].split("-")[3][0] == '1':
            labels.append(0)
        else:
            labels.append(1)
    except:
        labels.append(-1)

In [90]:
len(labels)

185

In [91]:
len(gt)

185

In [92]:
labels

[-1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1]

In [93]:
u,c = np.unique(np.array(labels), return_counts = True)

In [94]:
u

array([-1,  0,  1])

In [95]:
c

array([  2,   4, 179], dtype=int64)

In [99]:
l[1]

array(['EntrezID', '100133144', '100134869', ..., '26009', '387590',
       '389932'], dtype='<U28')

In [61]:
l2[3]

['75119D1A-93E5-4AE7-9D60-69EE929A0772',
 'TCGA-2J-AAB1',
 '2014-7-16',
 'YES',
 'Pancreas-Adenocarcinoma-Other Subtype',
 'invasive adenocarcinoma',
 'Primary',
 'NO',
 'YES',
 'MALE',
 '-23962',
 'WHITE',
 '[Unknown]',
 'No',
 'No',
 '2012',
 'Tumor resection',
 '[Not Applicable]',
 'Whipple',
 'YES',
 '22',
 '7',
 '0',
 'G3',
 'Four Tier',
 '4.5',
 'R0',
 '7th',
 'T3',
 'N1',
 'M0',
 'Stage IIB',
 'Dead',
 '[Not Available]',
 '66',
 'TUMOR FREE',
 'Pancreatic Cancer',
 'Medical Record',
 '3',
 '1962',
 '1988',
 '25',
 'YES',
 'Weekly Drinker',
 '3',
 '1',
 'NO',
 '[Not Available]',
 'NO',
 '[Not Available]',
 'NO',
 '[Not Available]',
 'NO',
 'Complete Remission/Response',
 'NO',
 '65',
 'Head of Pancreas',
 '[Not Applicable]',
 '[Not Applicable]',
 '[Not Applicable]',
 '[Not Applicable]',
 '[Not Applicable]',
 '0',
 '[Not Available]',
 '[Not Available]',
 '[Not Available]',
 '[Not Applicable]',
 'C25.0',
 '8480/3',
 'C25.0',
 'YES',
 'AAB1',
 '[Not Available]',
 '[Not Available]',


In [104]:
data = l[2:]
labels = labels[2:]

In [105]:
data[0]

array(['TCGA-2J-AAB1-01A-11R-A41B-07', '8.5512', '8.522', ..., '616.0976',
       '45.3659', '0'], dtype='<U28')

In [106]:
l[2]

array(['TCGA-2J-AAB1-01A-11R-A41B-07', '8.5512', '8.522', ..., '616.0976',
       '45.3659', '0'], dtype='<U28')

In [109]:
u,c = np.unique(labels, return_counts = True)

In [110]:
u

array([0, 1])

In [111]:
c

array([  4, 179], dtype=int64)

In [112]:
len(data)

183

In [113]:
data = data[:,1:]

In [114]:
data[0]

array(['8.5512', '8.522', '110.7707', ..., '616.0976', '45.3659', '0'],
      dtype='<U28')

In [117]:
import pandas as pd 
pd.DataFrame(l).to_csv("file.csv")

In [118]:
pd.DataFrame(l[:,29:]).to_csv("file2.csv")

In [119]:
loo = l[:,29:]

In [120]:
dt = data[:,28:]

In [121]:
dt[0]

array(['81.9122', '25.3659', '0.4878', ..., '616.0976', '45.3659', '0'],
      dtype='<U28')

In [124]:
loo[2]

array(['81.9122', '25.3659', '0.4878', ..., '616.0976', '45.3659', '0'],
      dtype='<U28')

In [125]:
pd.DataFrame(labels).to_csv("label.csv")

In [126]:
pd.DataFrame(dt).to_csv("data.csv")

In [127]:
len(dt)

183

In [128]:
len(labels)

183

In [132]:
pd.DataFrame(l[0]).to_csv("dct.csv")