In [1]:
import numpy as np
import copy

In [2]:
f = open("KICH__RNAExp.txt","r")

In [3]:
f

<_io.TextIOWrapper name='KICH__RNAExp.txt' mode='r' encoding='cp1252'>

In [4]:
dt = f.readlines()

In [5]:
l = []
for i in range(len(dt)):
    l.append(dt[i].split("\t"))

In [6]:
f.close()

In [7]:
len(l)

20531

In [8]:
l[34][92]

'5835.9632\n'

In [9]:
for i in range(len(l)):
    l[i][92] = l[i][92].split("\n")[0]

In [10]:
l[0]

['GeneSymbol',
 'EntrezID',
 'TCGA-KL-8323-01A-21R-2315-07',
 'TCGA-KL-8324-01A-11R-2315-07',
 'TCGA-KL-8324-11A-01R-2315-07',
 'TCGA-KL-8325-01A-11R-2315-07',
 'TCGA-KL-8326-01A-11R-2315-07',
 'TCGA-KL-8326-11A-01R-2315-07',
 'TCGA-KL-8327-01A-11R-2315-07',
 'TCGA-KL-8328-01A-11R-2315-07',
 'TCGA-KL-8329-01A-11R-2315-07',
 'TCGA-KL-8329-11A-01R-2315-07',
 'TCGA-KL-8330-01A-11R-2315-07',
 'TCGA-KL-8331-01A-11R-2315-07',
 'TCGA-KL-8332-01A-11R-2315-07',
 'TCGA-KL-8332-11A-01R-2315-07',
 'TCGA-KL-8333-01A-11R-2315-07',
 'TCGA-KL-8334-01A-11R-2315-07',
 'TCGA-KL-8335-01A-11R-2315-07',
 'TCGA-KL-8336-01A-11R-2315-07',
 'TCGA-KL-8336-11A-01R-2315-07',
 'TCGA-KL-8337-01A-11R-2315-07',
 'TCGA-KL-8338-01A-11R-2315-07',
 'TCGA-KL-8339-01A-11R-2315-07',
 'TCGA-KL-8339-11A-01R-2315-07',
 'TCGA-KL-8340-01A-11R-2315-07',
 'TCGA-KL-8341-01A-11R-2315-07',
 'TCGA-KL-8342-01A-11R-2315-07',
 'TCGA-KL-8343-01A-11R-2315-07',
 'TCGA-KL-8344-01A-11R-2315-07',
 'TCGA-KL-8345-01A-11R-2315-07',
 'TCGA-KL-8346-

In [11]:
l[1]

['?',
 '100133144',
 '8.8472',
 '10.2397',
 '7.1989',
 '6.0252',
 '1.6957',
 '4.2791',
 '2.8302',
 '1.7671',
 '2.2676',
 '3.6995',
 '5.2891',
 '1.8747',
 '0',
 '0.7535',
 '5.9159',
 '8.0585',
 '3.7604',
 '3.7819',
 '3.8314',
 '1.8971',
 '0.8741',
 '22.5036',
 '6.2177',
 '3.3939',
 '15.9047',
 '1.0328',
 '8.2147',
 '8.5501',
 '3.3798',
 '0.8599',
 '2.5567',
 '0.9789',
 '3.7978',
 '0',
 '14.2178',
 '7.3859',
 '2.741',
 '8.296',
 '2.993',
 '10.8591',
 '6.2837',
 '1.2053',
 '4.7507',
 '1.7804',
 '3.6778',
 '0',
 '6.1941',
 '15.349',
 '3.256',
 '8',
 '7.9298',
 '30.7276',
 '11.4151',
 '21.4202',
 '3.8193',
 '21.1208',
 '2.67',
 '8.8466',
 '2.288',
 '14.8016',
 '6.1628',
 '0',
 '3.1434',
 '9.6729',
 '5.5357',
 '8.177',
 '6.1649',
 '6.161',
 '0.9934',
 '30.399',
 '6.4548',
 '17.2822',
 '2.0853',
 '2.701',
 '4.6397',
 '4.4464',
 '11.9308',
 '4.9342',
 '0.4801',
 '3.5704',
 '7.8356',
 '7.1955',
 '6.1565',
 '8.8693',
 '3.2566',
 '11.5483',
 '3.2197',
 '0.5373',
 '7.5991',
 '1.3153',
 '2.7337']

In [12]:
l = np.array(l).T

In [13]:
l

array([['GeneSymbol', '?', '?', ..., 'ZZZ3', 'psiTPTE22', 'tAKR'],
       ['EntrezID', '100133144', '100134869', ..., '26009', '387590',
        '389932'],
       ['TCGA-KL-8323-01A-21R-2315-07', '8.8472', '5.5126', ...,
        '592.7403', '1.9944', '8.3765'],
       ...,
       ['TCGA-KO-8415-11A-01R-2315-07', '7.5991', '10.7784', ...,
        '914.7378', '273.3646', '0'],
       ['TCGA-KO-8416-01A-11R-2315-07', '1.3153', '3.4197', ...,
        '376.1673', '583.4539', '0.5261'],
       ['TCGA-KO-8417-01A-11R-2315-07', '2.7337', '3.9943', ...,
        '651.5581', '474.5042', '0']], dtype='<U28')

In [14]:
gt = copy.deepcopy(l)

In [15]:
gt[0][0].split('-')

['GeneSymbol']

In [16]:
labels = []

for i in range(len(gt)):
    try:
        if gt[i][0].split("-")[3][0] == '1':
            labels.append(0)
        else:
            labels.append(1)
    except:
        labels.append(-1)

In [17]:
len(labels)

93

In [18]:
len(gt)

93

In [19]:
labels

[-1,
 -1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1]

In [20]:
u,c = np.unique(np.array(labels), return_counts = True)

In [21]:
u

array([-1,  0,  1])

In [22]:
c

array([ 2, 25, 66], dtype=int64)

In [23]:
l[1]

array(['EntrezID', '100133144', '100134869', ..., '26009', '387590',
       '389932'], dtype='<U28')

In [24]:
l[2]

array(['TCGA-KL-8323-01A-21R-2315-07', '8.8472', '5.5126', ...,
       '592.7403', '1.9944', '8.3765'], dtype='<U28')

In [25]:
data = l[2:]
labels = labels[2:]

In [26]:
data[0]

array(['TCGA-KL-8323-01A-21R-2315-07', '8.8472', '5.5126', ...,
       '592.7403', '1.9944', '8.3765'], dtype='<U28')

In [27]:
l[2]

array(['TCGA-KL-8323-01A-21R-2315-07', '8.8472', '5.5126', ...,
       '592.7403', '1.9944', '8.3765'], dtype='<U28')

In [28]:
u,c = np.unique(labels, return_counts = True)

In [29]:
u

array([0, 1])

In [30]:
c

array([25, 66], dtype=int64)

In [31]:
len(data)

91

In [111]:
data = data[:,1:]

In [112]:
data[0]

array(['8.8472', '5.5126', '98.6478', ..., '592.7403', '1.9944', '8.3765'],
      dtype='<U28')

In [113]:
import pandas as pd 
pd.DataFrame(l).to_csv("kichfile.csv")

In [114]:
pd.DataFrame(l[:,29:]).to_csv("kichfile2.csv")

In [115]:
loo = l[:,29:]

In [116]:
dt = data[:,28:]

In [117]:
dt[0]

array(['9.1903', '0', '0', ..., '592.7403', '1.9944', '8.3765'],
      dtype='<U28')

In [118]:
loo[2]

array(['9.1903', '0', '0', ..., '592.7403', '1.9944', '8.3765'],
      dtype='<U28')

In [119]:
pd.DataFrame(labels).to_csv("kichlabel.csv")

In [120]:
pd.DataFrame(dt).to_csv("kichdata.csv")

In [121]:
len(dt)

91

In [122]:
len(labels)

91