In [49]:
import numpy as np
import copy

In [50]:
f = open("KIRC__RNAExp.txt","r")

In [51]:
f

<_io.TextIOWrapper name='KIRC__RNAExp.txt' mode='r' encoding='cp1252'>

In [52]:
dt = f.readlines()

In [53]:
l = []
for i in range(len(dt)):
    l.append(dt[i].split("\t"))

In [54]:
f.close()

In [55]:
len(l)

20531

In [56]:
len(l[34])

608

In [57]:
l[34][607]

'4996.8621\n'

In [58]:
for i in range(len(l)):
    l[i][607] = l[i][607].split("\n")[0]

In [59]:
l[0]

['GeneSymbol',
 'EntrezID',
 'TCGA-3Z-A93Z-01A-11R-A37O-07',
 'TCGA-6D-AA2E-01A-11R-A37O-07',
 'TCGA-A3-3306-01A-01R-0864-07',
 'TCGA-A3-3307-01A-01R-0864-07',
 'TCGA-A3-3308-01A-02R-1325-07',
 'TCGA-A3-3311-01A-02R-1325-07',
 'TCGA-A3-3313-01A-02R-1325-07',
 'TCGA-A3-3316-01A-01R-0864-07',
 'TCGA-A3-3317-01A-02R-1325-07',
 'TCGA-A3-3319-01A-02R-1325-07',
 'TCGA-A3-3320-01A-02R-1325-07',
 'TCGA-A3-3322-01A-02R-1325-07',
 'TCGA-A3-3323-01A-02R-1325-07',
 'TCGA-A3-3324-01A-02R-1325-07',
 'TCGA-A3-3325-01A-01R-0864-07',
 'TCGA-A3-3326-01A-01R-0864-07',
 'TCGA-A3-3328-01A-01R-0864-07',
 'TCGA-A3-3329-01A-01R-0864-07',
 'TCGA-A3-3331-01A-02R-1325-07',
 'TCGA-A3-3335-01A-01R-0864-07',
 'TCGA-A3-3343-01A-01R-0864-07',
 'TCGA-A3-3346-01A-01R-1766-07',
 'TCGA-A3-3347-01A-02R-1325-07',
 'TCGA-A3-3349-01A-01R-1188-07',
 'TCGA-A3-3351-01A-02R-1325-07',
 'TCGA-A3-3352-01A-01R-0864-07',
 'TCGA-A3-3357-01A-02R-1420-07',
 'TCGA-A3-3358-01A-01R-1541-07',
 'TCGA-A3-3358-11A-01R-1541-07',
 'TCGA-A3-3359-

In [60]:
l[1]

['?',
 '100133144',
 '2.9608',
 '2.4501',
 '3.2246',
 '1.8578',
 '6.464',
 '10.4052',
 '6.51',
 '14.6871',
 '16.5597',
 '10.6939',
 '12.7718',
 '27.1325',
 '19.2964',
 '16.7843',
 '6.762',
 '1.8298',
 '13.4699',
 '5.6123',
 '14.3855',
 '4.4719',
 '6.0274',
 '8.91',
 '8.8393',
 '6.4037',
 '19.6159',
 '2.619',
 '18.1782',
 '6.5394',
 '3.209',
 '12.6008',
 '10.3643',
 '8.4939',
 '1.045',
 '16.6741',
 '14.2881',
 '15.2503',
 '5.8556',
 '0',
 '5.5267',
 '20.4623',
 '3.7197',
 '4.5273',
 '4.7742',
 '12.4808',
 '8.304',
 '1.4905',
 '5.6045',
 '4.3457',
 '12.6998',
 '19.9732',
 '7.6278',
 '7.5498',
 '5.2304',
 '1.6206',
 '8.123',
 '5.0783',
 '6.7803',
 '0.577',
 '2.8011',
 '0.9603',
 '10.4323',
 '10.4525',
 '1.6527',
 '4.972',
 '2.5778',
 '5.2188',
 '2.4435',
 '8.8106',
 '5.5885',
 '4.6719',
 '0',
 '7.1232',
 '16.3003',
 '0.6639',
 '5.388',
 '5.4436',
 '7.1867',
 '5.8672',
 '2.7683',
 '2.22',
 '7.983',
 '13.8599',
 '18.2694',
 '3.185',
 '13.4108',
 '1.0226',
 '15.5869',
 '1.7041',
 '5.9502',
 

In [61]:
l = np.array(l).T

In [62]:
l

array([['GeneSymbol', '?', '?', ..., 'ZZZ3', 'psiTPTE22', 'tAKR'],
       ['EntrezID', '100133144', '100134869', ..., '26009', '387590',
        '389932'],
       ['TCGA-3Z-A93Z-01A-11R-A37O-07', '2.9608', '11.4669', ...,
        '493.0527', '38.8922', '0'],
       ...,
       ['TCGA-MM-A84U-01A-11R-A37O-07', '2.7042', '8.5634', ...,
        '548.7324', '640', '0'],
       ['TCGA-MW-A4EC-01A-11R-A266-07', '12.5228', '8.3895', ...,
        '485.9047', '21.7324', '0'],
       ['TCGA-T7-A92I-01A-11R-A37O-07', '3.8379', '9.6231', ...,
        '488.7825', '273.7063', '0']], dtype='<U28')

In [63]:
gt = copy.deepcopy(l)

In [64]:
gt[0][0].split('-')

['GeneSymbol']

In [65]:
labels = []

for i in range(len(gt)):
    try:
        if gt[i][0].split("-")[3][0] == '1':
            labels.append(0)
        else:
            labels.append(1)
    except:
        labels.append(-1)

In [66]:
len(labels)

608

In [67]:
len(gt)

608

In [68]:
labels

[-1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1

In [69]:
u,c = np.unique(np.array(labels), return_counts = True)

In [70]:
u

array([-1,  0,  1])

In [71]:
c

array([  2,  72, 534], dtype=int64)

In [72]:
l[1]

array(['EntrezID', '100133144', '100134869', ..., '26009', '387590',
       '389932'], dtype='<U28')

In [73]:
l[2]

array(['TCGA-3Z-A93Z-01A-11R-A37O-07', '2.9608', '11.4669', ...,
       '493.0527', '38.8922', '0'], dtype='<U28')

In [74]:
data = l[2:]
labels = labels[2:]

In [75]:
data[0]

array(['TCGA-3Z-A93Z-01A-11R-A37O-07', '2.9608', '11.4669', ...,
       '493.0527', '38.8922', '0'], dtype='<U28')

In [76]:
l[2]

array(['TCGA-3Z-A93Z-01A-11R-A37O-07', '2.9608', '11.4669', ...,
       '493.0527', '38.8922', '0'], dtype='<U28')

In [77]:
u,c = np.unique(labels, return_counts = True)

In [78]:
u

array([0, 1])

In [79]:
c

array([ 72, 534], dtype=int64)

In [80]:
len(data)

606

In [81]:
data = data[:,1:]

In [82]:
data[0]

array(['2.9608', '11.4669', '75.7771', ..., '493.0527', '38.8922', '0'],
      dtype='<U28')

In [83]:
import pandas as pd 
pd.DataFrame(l).to_csv("kircfile.csv")

In [84]:
pd.DataFrame(l[:,29:]).to_csv("kircfile2.csv")

In [85]:
loo = l[:,29:]

In [86]:
dt = data[:,28:]

In [87]:
dt[0]

array(['194.9691', '96.6032', '1.8819', ..., '493.0527', '38.8922', '0'],
      dtype='<U28')

In [88]:
loo[2]

array(['194.9691', '96.6032', '1.8819', ..., '493.0527', '38.8922', '0'],
      dtype='<U28')

In [89]:
pd.DataFrame(labels).to_csv("kirclabel.csv")

In [90]:
pd.DataFrame(dt).to_csv("kircdata.csv")

In [91]:
len(dt)

606

In [92]:
len(labels)

606