In [1]:
import numpy as np
import copy

In [2]:
f = open("KIRP__RNAExp.txt","r")

In [3]:
f

<_io.TextIOWrapper name='KIRP__RNAExp.txt' mode='r' encoding='cp1252'>

In [4]:
dt = f.readlines()

In [5]:
l = []
for i in range(len(dt)):
    l.append(dt[i].split("\t"))

In [6]:
f.close()

In [7]:
len(l)

20531

In [8]:
len(l[34])

325

In [10]:
l[34][324]

'38294.8786\n'

In [11]:
for i in range(len(l)):
    l[i][324] = l[i][324].split("\n")[0]

In [12]:
l[0]

['GeneSymbol',
 'EntrezID',
 'TCGA-2K-A9WE-01A-11R-A38C-07',
 'TCGA-2Z-A9J1-01A-11R-A38C-07',
 'TCGA-2Z-A9J2-01A-11R-A38C-07',
 'TCGA-2Z-A9J3-01A-12R-A38C-07',
 'TCGA-2Z-A9J5-01A-21R-A38C-07',
 'TCGA-2Z-A9J6-01A-11R-A38C-07',
 'TCGA-2Z-A9J7-01A-11R-A38C-07',
 'TCGA-2Z-A9J8-01A-11R-A42S-07',
 'TCGA-2Z-A9J9-01A-11R-A42S-07',
 'TCGA-2Z-A9JD-01A-11R-A42S-07',
 'TCGA-2Z-A9JE-01A-11R-A42S-07',
 'TCGA-2Z-A9JG-01A-11R-A42S-07',
 'TCGA-2Z-A9JI-01A-11R-A42S-07',
 'TCGA-2Z-A9JJ-01A-11R-A42S-07',
 'TCGA-2Z-A9JK-01A-11R-A42S-07',
 'TCGA-2Z-A9JL-01A-11R-A42S-07',
 'TCGA-2Z-A9JM-01A-12R-A42S-07',
 'TCGA-2Z-A9JN-01A-21R-A42S-07',
 'TCGA-2Z-A9JO-01A-11R-A42S-07',
 'TCGA-2Z-A9JP-01A-11R-A42S-07',
 'TCGA-2Z-A9JQ-01A-11R-A42S-07',
 'TCGA-2Z-A9JR-01A-12R-A42S-07',
 'TCGA-2Z-A9JS-01A-21R-A42S-07',
 'TCGA-2Z-A9JT-01A-11R-A42S-07',
 'TCGA-4A-A93W-01A-11R-A37K-07',
 'TCGA-4A-A93X-01A-11R-A37K-07',
 'TCGA-4A-A93Y-01A-11R-A37K-07',
 'TCGA-5P-A9JU-01A-11R-A42S-07',
 'TCGA-5P-A9JV-01A-12R-A42S-07',
 'TCGA-5P-A9JW-

In [13]:
l[1]

['?',
 '100133144',
 '5.0494',
 '8.0387',
 '2.8619',
 '5.8053',
 '1.3098',
 '10.1249',
 '9.2934',
 '7.8431',
 '9.1399',
 '9.5539',
 '6.6314',
 '9.7467',
 '9.1998',
 '15.1856',
 '12.4712',
 '37.5259',
 '16.5285',
 '2.5942',
 '1.0473',
 '0',
 '7.5364',
 '20.2035',
 '22.3933',
 '1.8009',
 '6.9446',
 '4.8491',
 '2.6388',
 '4.607',
 '6.3222',
 '6.7364',
 '5.1797',
 '12.75',
 '11.4569',
 '4.3894',
 '9.8005',
 '9.3439',
 '18.4038',
 '3.7194',
 '12.7867',
 '29.7625',
 '8.3251',
 '5.7169',
 '28.6595',
 '8.3512',
 '0',
 '12.5596',
 '5.8366',
 '9.8907',
 '8.1723',
 '2.0096',
 '13.4885',
 '20',
 '3.3675',
 '0.7762',
 '17.2092',
 '10.3428',
 '3.3794',
 '5.3775',
 '17.2818',
 '0.8653',
 '5.2734',
 '4.6884',
 '12.0562',
 '1.807',
 '13.2994',
 '0',
 '7.8188',
 '11.3893',
 '4.569',
 '2.0146',
 '5.4994',
 '10.0587',
 '13.5275',
 '6.3238',
 '11.129',
 '5.5174',
 '10.432',
 '22.0707',
 '20.283',
 '18.5194',
 '35.0768',
 '5.9262',
 '3.2042',
 '8.0767',
 '2.832',
 '6.6941',
 '1.5909',
 '5.5398',
 '5.7389',


In [14]:
l = np.array(l).T

In [15]:
l

array([['GeneSymbol', '?', '?', ..., 'ZZZ3', 'psiTPTE22', 'tAKR'],
       ['EntrezID', '100133144', '100134869', ..., '26009', '387590',
        '389932'],
       ['TCGA-2K-A9WE-01A-11R-A38C-07', '5.0494', '5.7378', ...,
        '978.0403', '270.1939', '0'],
       ...,
       ['TCGA-Y8-A8RZ-01A-11R-A37K-07', '4.1915', '14.6134', ...,
        '792.775', '8.9076', '0'],
       ['TCGA-Y8-A8S0-01A-11R-A37K-07', '21.3229', '22.5127', ...,
        '753.816', '261.8395', '0'],
       ['TCGA-Y8-A8S1-01A-11R-A37K-07', '0.7143', '0', ..., '209.2857',
        '23.5714', '0']], dtype='<U28')

In [16]:
gt = copy.deepcopy(l)

In [20]:
gt[0][0].split('-')

['GeneSymbol']

In [21]:
labels = []

for i in range(len(gt)):
    try:
        if gt[i][0].split("-")[3][0] == '1':
            labels.append(0)
        else:
            labels.append(1)
    except:
        labels.append(-1)

In [22]:
len(labels)

325

In [23]:
len(gt)

325

In [24]:
labels

[-1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1

In [25]:
u,c = np.unique(np.array(labels), return_counts = True)

In [26]:
u

array([-1,  0,  1])

In [27]:
c

array([  2,  32, 291], dtype=int64)

In [28]:
l[1]

array(['EntrezID', '100133144', '100134869', ..., '26009', '387590',
       '389932'], dtype='<U28')

In [29]:
l[2]

array(['TCGA-2K-A9WE-01A-11R-A38C-07', '5.0494', '5.7378', ...,
       '978.0403', '270.1939', '0'], dtype='<U28')

In [30]:
data = l[2:]
labels = labels[2:]

In [31]:
data[0]

array(['TCGA-2K-A9WE-01A-11R-A38C-07', '5.0494', '5.7378', ...,
       '978.0403', '270.1939', '0'], dtype='<U28')

In [32]:
l[2]

array(['TCGA-2K-A9WE-01A-11R-A38C-07', '5.0494', '5.7378', ...,
       '978.0403', '270.1939', '0'], dtype='<U28')

In [33]:
u,c = np.unique(labels, return_counts = True)

In [34]:
u

array([0, 1])

In [35]:
c

array([ 32, 291], dtype=int64)

In [36]:
len(data)

323

In [37]:
data = data[:,1:]

In [38]:
data[0]

array(['5.0494', '5.7378', '54.6809', ..., '978.0403', '270.1939', '0'],
      dtype='<U28')

In [39]:
import pandas as pd 
pd.DataFrame(l).to_csv("kirpfile.csv")

In [40]:
pd.DataFrame(l[:,29:]).to_csv("kirpfile2.csv")

In [41]:
loo = l[:,29:]

In [42]:
dt = data[:,28:]

In [43]:
dt[0]

array(['201.3304', '4.1094', '0.5137', ..., '978.0403', '270.1939', '0'],
      dtype='<U28')

In [44]:
loo[2]

array(['201.3304', '4.1094', '0.5137', ..., '978.0403', '270.1939', '0'],
      dtype='<U28')

In [45]:
pd.DataFrame(labels).to_csv("kirplabel.csv")

In [46]:
pd.DataFrame(dt).to_csv("kirpdata.csv")

In [47]:
len(dt)

323

In [48]:
len(labels)

323